# Generated by Django 5.1.2 on 2025-09-17 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('resumo', models.TextField()),
                ('abstract', models.TextField()),
                ('palavras_chave', models.CharField(max_length=255)),
                ('documento_pdf', models.FileField(upload_to='monografias_pdf/')),
                ('status', models.CharField(choices=[('EM_AVALIACAO', 'Em Avaliação'), ('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado'), ('CORRECAO', 'Em Correção')], default='EM_AVALIACAO', max_length=20)),
                ('data_defesa', models.DateField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.aluno')),
                ('coorientador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coorientacoes', to='users.professor')),
                ('orientador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orientacoes', to='users.professor')),
            ],
        ),
        migrations.CreateModel(
            name='Banca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_defesa', models.DateTimeField()),
                ('local_defesa', models.CharField(max_length=100)),
                ('nota_final', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('avaliadores', models.ManyToManyField(to='users.professor')),
                ('monografia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='monografias.monografia')),
            ],
        ),
    ]
